config/routes.rb
RustServers::Application.routes.draw do
  get 'my-servers' => 'servers#my_servers', as: :my_servers
  get 'popular-servers' => 'servers#popular_servers', as: :popular_servers
  get 'server/:id/vote' => 'servers#get_vote', as: :get_vote
  post 'server/:id/vote' => 'servers#post_vote', as: :post_vote

  resources :servers

  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
        get :cancel
      end
  end

  root 'home#index'

end

app/models/server.rb
class Server < ActiveRecord::Base
  # relationships
  belongs_to :user
  has_many :votes
  has_many :uptime_checks

  # scopes
  scope :recent, -> { order('created_at DESC') }
  scope :for_user, lambda { |user_id| where(user_id: user_id) }

  # validations
  validates :ip, presence: true, format: { with: /[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\:[0-9]{1,5}/ }
  validates :name, presence: true, length: { maximum: 40, minimum: 5 }
  validates :description, presence: true, length: { maximum: 500 }

end

app/models/uptime_check.rb
class UptimeCheck < ActiveRecord::Base
  belongs_to :server
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :servers, dependent: :destroy

  validate :username, presence: true, uniqueness: true, format: { with: /[a-zA-Z0-9]{4,20}/ }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  scope :get_12_hour_votes, -> { where(created_at: 12.hours.ago..Time.zone.now)}

  validate :check_ip

  belongs_to :server

  private
  def check_ip
    errors.add(:base, 'You\'ve already voted today, please wait 12 hours before voting again.') unless Vote.where(ip: ip).where(server_id: server_id).get_12_hour_votes.length == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :username
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @servers = Server.recent
  end
  
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy, :get_vote, :post_vote]
  before_filter :authenticate_user!, except: [:index, :show, :popular_servers]
  before_filter :is_mine, only: [:edit, :update]
  before_filter :set_vote, only: [:get_vote, :post_vote]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show

  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)
    @server.user = current_user

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url }
    end
  end

  def my_servers
    @servers = Server.for_user(current_user.id).recent
  end

  def popular_servers 
    @servers = Server.all
  end

  def get_vote
    
  end

  def post_vote 
    @vote.ip = request.remote_ip
    @vote.server = @server

    respond_to do |format| 
      if verify_recaptcha && @vote.save
        format.html { 
          flash[:notice] = "You've voted for #{@server.name}!" 
          redirect_to @server 
        }
      else
        format.html { render 'get_vote' }
      end
    end
  end

  private
    def set_vote 
      @vote = Vote.new
    end

    def is_mine
      redirect_to(root_path) if @server.user_id != current_user.id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.includes(:user).includes(:votes).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :description, :ip)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/servers_helper.rb
module ServersHelper

  def is_mine(server)
    if user_signed_in?
      if current_user.id == server.user_id 
        true
      end
      false
    end
    false
  end
end

app/views/home/index.html.erb
<%= render 'servers/index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body data-no-turbolink>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'Top Rust Servers', root_path %></h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <% if user_signed_in? %>
            <li><%= link_to 'New server', new_server_path %></li>
            <li><%= link_to 'My servers', my_servers_path %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Login', new_user_session_path %></li>
          <% end %>
          <li><%= link_to 'List all servers', servers_path %></li>
          <li><%= link_to 'List popular servers', popular_servers_path %></li>
          <% if user_signed_in? %>
            <li class="has-dropdown">
              <a href="#">Welcome <%= current_user.username %></a>
              <ul class="dropdown">
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </section>
    </nav>


    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    
    <%= yield %>

    
    <% if Rails.env.production? %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-48125754-1', 'rust-servers.info');
      ga('send', 'pageview');

    </script>
    <% end %>
  </body>
</html>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/_index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.description %></td>
        <td><%= server.user_id %></td>
        <td>
          <%= link_to 'Show', server %>
        </td>
        <td>
          <% if is_mine(server) %>
            <%= link_to 'Edit', edit_server_path(server) %>
          <% end %>
        </td>
        <td>
          <% if is_mine(server) %>
            <%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/get_vote.html.erb
<h2>You are voting for <%= link_to @server.name, @server %></h2>
<%= form_tag(post_vote_path(@server), method: :post) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>Please enter the following captcha before proceeding</p>
  <%= recaptcha_tags %>
  <%= submit_tag 'Vote' %>
<% end %>

app/views/servers/index.html.erb
<%= render 'index' %>

app/views/servers/my_servers.html.erb
<%= render 'index' %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/popular_servers.html.erb
<%= render 'index' %>

app/views/servers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @server.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @server.user.username %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @server.votes.count %>
</p>

<%= link_to 'Vote this server', get_vote_path(@server) %>

<% if is_mine(@server) %>
  <%= link_to 'Edit', edit_server_path(@server) %> |
<% end %>
<%= link_to 'Back', servers_path %>